-- Paste these entries into ox_inventory/data/items.lua (inside the main items table)
-- consume + server.export required for hunger/thirst/stress via viking_foodtruck

['taco'] = {
    label = 'Street Taco',
    weight = 180,
    stack = true,
    close = true,
    consume = 1,
    description = 'A freshly made street taco from a food truck.',
    server = { export = 'viking_foodtruck.usedFoodItem' },
    client = { image = 'taco.png', status = { hunger = 250000 }, usetime = 3500 },
},
['burrito'] = {
    label = 'Beef Burrito',
    weight = 280,
    stack = true,
    close = true,
    consume = 1,
    description = 'A hearty beef burrito.',
    server = { export = 'viking_foodtruck.usedFoodItem' },
    client = { image = 'burrito.png', status = { hunger = 400000 }, usetime = 4500 },
},
['burger'] = {
    label = 'Classic Burger',
    weight = 220,
    stack = true,
    close = true,
    consume = 1,
    description = 'A greasy classic burger.',
    server = { export = 'viking_foodtruck.usedFoodItem' },
    client = { image = 'burger.png', status = { hunger = 350000 }, usetime = 4000 },
},
['fries'] = {
    label = 'Fries',
    weight = 120,
    stack = true,
    close = true,
    consume = 1,
    description = 'Crispy fries.',
    server = { export = 'viking_foodtruck.usedFoodItem' },
    client = { image = 'fries.png', status = { hunger = 150000 }, usetime = 3000 },
},
['hotdog'] = {
    label = 'Hotdog',
    weight = 160,
    stack = true,
    close = true,
    consume = 1,
    description = 'A classic hotdog.',
    server = { export = 'viking_foodtruck.usedFoodItem' },
    client = { image = 'hotdog.png', status = { hunger = 200000 }, usetime = 3000 },
},
['water'] = {
    label = 'Water',
    weight = 200,
    stack = true,
    close = true,
    consume = 1,
    description = 'A bottle of water.',
    server = { export = 'viking_foodtruck.usedFoodItem' },
    client = { image = 'water.png', status = { thirst = 300000 }, usetime = 2500 },
},
['cola'] = {
    label = 'Cola',
    weight = 200,
    stack = true,
    close = true,
    consume = 1,
    description = 'An ice-cold cola.',
    server = { export = 'viking_foodtruck.usedFoodItem' },
    client = { image = 'cola.png', status = { thirst = 250000 }, usetime = 2500 },
},
